#!/usr/bin/env python3
"""Render generated status documentation from canonical machine-readable sources.

Reads:
  - artifacts/proof/current/source_registry_status.json
  - artifacts/proof/current/release_gate.json
  - artifacts/proof/current/proof_manifest.json (optional)

Outputs:
  - docs/generated/SOURCE_STATUS.md
  - docs/generated/PROOF_SUMMARY.md
  - docs/generated/RELEASE_STATUS.md

Usage::

    python3 scripts/render_status_docs.py
    python3 scripts/render_status_docs.py --root /path/to/repo
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def _load_json(path: Path) -> dict | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"WARNING: failed to parse {path}: {exc}", file=sys.stderr)
        return None


def _now_utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def render_source_status(registry: dict, output_path: Path) -> None:
    summary = registry.get("summary", {})
    total = summary.get("total_sources", registry.get("total_sources", "?"))
    runnable = summary.get("runnable_now", "?")
    enable_ready = summary.get("enable_ready", "?")
    machine_ingest = summary.get("machine_ingest_sources", "?")
    deprecated = summary.get("deprecated", "?")
    generated_at = registry.get("generated_at_utc", "unknown")

    lines = [
        "<!-- AUTO-GENERATED by scripts/render_status_docs.py — do not edit manually -->",
        "# Source Registry Status",
        "",
        f"> Generated: {generated_at}",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total sources | {total} |",
        f"| Machine-ingest sources | {machine_ingest} |",
        f"| Runnable now | {runnable} |",
        f"| Enable-ready | {enable_ready} |",
        f"| Deprecated | {deprecated} |",
        "",
        "## Sources",
        "",
        "| Key | Name | Status | Machine Ingest | Runnable |",
        "|-----|------|--------|----------------|---------|",
    ]

    for src in registry.get("sources", []):
        key = src.get("source_key", "?")
        name = src.get("source_name", "?")
        state = src.get("lifecycle_state", src.get("alpha_status", "?"))
        mi = "yes" if src.get("source_class") == "machine_ingest" else "no"
        run = "yes" if src.get("runnable_now") else "no"
        lines.append(f"| `{key}` | {name} | {state} | {mi} | {run} |")

    lines.append("")
    lines.append(
        "> **Authority**: `artifacts/proof/current/source_registry_status.json`"
    )
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written: {output_path}")


def render_proof_summary(gate: dict, _manifest: dict | None, output_path: Path) -> None:
    generated_at = gate.get("generated_at", gate.get("timestamp_utc", "unknown"))
    alpha_passed = gate.get("alpha_gate_passed", False)
    self_verifying = gate.get("self_verifying_alpha", False)
    prod_ready = gate.get("production_ready", False)
    public_safe = gate.get("public_release_safe", False)
    backend_tests = gate.get("backend_tests_passed", gate.get("backend_compile_passed"))
    frontend_build = gate.get("frontend_build_passed")
    proof_fresh = gate.get("proof_freshness_passed")
    check_count = gate.get("check_count", "?")
    backend_count = gate.get("backend_test_count", "?")
    frontend_count = gate.get("frontend_contract_count", "?")

    def _bool(v: object) -> str:
        if v is True:
            return "PASS"
        if v is False:
            return "FAIL"
        return "unknown"

    lines = [
        "<!-- AUTO-GENERATED by scripts/render_status_docs.py — do not edit manually -->",
        "# Proof Summary",
        "",
        f"> Generated: {generated_at}",
        "",
        "## Gate Results",
        "",
        "| Check | Result |",
        "|-------|--------|",
        f"| Alpha gate | {_bool(alpha_passed)} |",
        f"| Self-verifying alpha | {_bool(self_verifying)} |",
        f"| Production ready | {_bool(prod_ready)} |",
        f"| Public release safe | {_bool(public_safe)} |",
        f"| Backend tests | {_bool(backend_tests)} |",
        f"| Frontend build | {_bool(frontend_build)} |",
        f"| Proof freshness | {_bool(proof_fresh)} |",
        "",
        "## Counts",
        "",
        f"- Gate checks: {check_count}",
        f"- Backend test count: {backend_count}",
        f"- Frontend contract count: {frontend_count}",
        "",
    ]

    blockers = gate.get("release_blockers_remaining", [])
    if blockers:
        lines.append("## Open Blockers")
        lines.append("")
        for b in blockers:
            lines.append(f"- {b}")
        lines.append("")

    known = gate.get("known_limitations", [])
    if known:
        lines.append("## Known Limitations")
        lines.append("")
        for lim in known:
            lines.append(f"- {lim}")
        lines.append("")

    lines.append("> **Authority**: `artifacts/proof/current/release_gate.json`")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written: {output_path}")


def render_release_status(gate: dict, registry: dict, output_path: Path) -> None:
    generated_at = gate.get("generated_at", gate.get("timestamp_utc", "unknown"))
    alpha_passed = gate.get("alpha_gate_passed", False)
    self_verifying = gate.get("self_verifying_alpha", False)
    prod_ready = gate.get("production_ready", False)
    public_safe = gate.get("public_release_safe", False)

    summary = registry.get("summary", {})
    total = summary.get("total_sources", "?")
    runnable = summary.get("runnable_now", "?")
    enable_ready = summary.get("enable_ready", "?")

    commit = gate.get("commit_hash", gate.get("git_commit", "unknown"))
    python_ver = gate.get("python_version", "?")
    node_ver = gate.get("node_version", "?")

    lines = [
        "<!-- AUTO-GENERATED by scripts/render_status_docs.py — do not edit manually -->",
        "# Release Status",
        "",
        f"> Generated: {generated_at}",
        "",
        "## Release Posture",
        "",
        f"- **Alpha gate passed**: {alpha_passed}",
        f"- **Self-verifying alpha**: {self_verifying}",
        f"- **Production ready**: {prod_ready}",
        f"- **Public release safe**: {public_safe}",
        "",
        "## Runtime",
        "",
        f"- Commit: `{commit}`",
        f"- Python: {python_ver}",
        f"- Node: {node_ver}",
        "",
        "## Source Coverage",
        "",
        f"- Total registered sources: {total}",
        f"- Runnable now: {runnable}",
        f"- Enable-ready: {enable_ready}",
        "",
        "> **Authority**: `artifacts/proof/current/release_gate.json`  ",
        "> Source counts: `artifacts/proof/current/source_registry_status.json`",
        "",
    ]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written: {output_path}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=str(REPO_ROOT), help="Repository root")
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()

    registry = _load_json(
        root / "artifacts" / "proof" / "current" / "source_registry_status.json"
    )
    gate = _load_json(
        root / "artifacts" / "proof" / "current" / "release_gate.json"
    )
    manifest = _load_json(
        root / "artifacts" / "proof" / "current" / "proof_manifest.json"
    )

    errors = 0
    if registry is None:
        print(
            "ERROR: artifacts/proof/current/source_registry_status.json not found",
            file=sys.stderr,
        )
        errors += 1
    if gate is None:
        print(
            "ERROR: artifacts/proof/current/release_gate.json not found",
            file=sys.stderr,
        )
        errors += 1
    if errors:
        return 1

    docs_generated = root / "docs" / "generated"

    render_source_status(registry, docs_generated / "SOURCE_STATUS.md")
    render_proof_summary(gate, manifest, docs_generated / "PROOF_SUMMARY.md")
    render_release_status(gate, registry, docs_generated / "RELEASE_STATUS.md")

    print("render_status_docs: all generated docs written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
